main: com.amoebaman.blocklobber.BlockLobber

name: BlockLobber
version: 1.2 (CB 1.4.5-R1.0)
author: AmoebaMan
description: Allows players to throw blocks

commands:

  lob-block:
    aliases: [lob, lobblock, blocklobber]
    description: Lobs a block
    usage: /lob <ID[:data]> <strength>
    permission: blocklobber.lob
    permissions-message: You dont have the permission to lob blocks!
    
  lob-preset:
    aliases: [lob-set, lobpreset, lobset, lob-preset, lobs]
    description: Defines a preset for lobbing blocks
    usage: |
           /lobs (mat|data|str) <value>
           /lobs <dir>
           /lobs <pos> [X] [Y] [Z] [world]
    permission: blocklobber.preset
    permissions-message: You dont have the permission to use lobber presets!
    
  lob-clear:
    aliases: [lobclear, lobc]
    description: Clears a previously defined preset
    usage: /lobc (pos|dir|mat|data|str|all)
    permission: blocklobber.preset
    permissions-message: You dont have the permission to use lobber presets!
    
  lob-projectile:
    aliases: [lobprojectile, lob-proj, lobproj, lobp]
    description: Lobs a projectile
    usage: /lobp <type> <strength>
    permission: blocklobber.projectile.lob
    permissions-message: You dont have the permission to lob projectiles!
    
  lob-projectile-preset:
    aliases: [lob-setp, lobpresetp, lobsetp, lob-presetp, lobsp]
    description: Defines a preset for lobbing projectile
    usage: |
           /lobsp (type|str) <value>
           /lobsp <dir>
           /lobsp <pos> [X] [Y] [Z] [world]
    permission: blocklobber.projectile.preset
    permissions-message: You dont have the permission to use projectile presets!
    
  lob-projectile-clear:
    aliases: [lobclearp, lobcp]
    description: Clears a previously defined projectile preset
    usage: /lobcp (pos|type|data|str)
    permission: blocklobber.projectile.preset
    permissions-message: You dont have the permission to use projectile presets!
    
  lob-reload:
    aliases: [lobreload, lobr]
    description: reloads config
    usage: /lobr
    permission: blocklobber.reload
    permissions-messages: You dont have the permission to reload config!
    
permissions:

  blocklobber.lob:
    description: Allows players to lob blocks
    default: op
    
  blocklobber.preset:
    description: Allows players to set presets for lobbing blocks
    default: op
    
  blocklobber.projectile.lob:
    description: Allows players to lob projectiles
    default: op
    
  blocklobber.projectile.preset:
    description: Allows players to lob projectiles
    default: op
      
  blocklobber.reload:
    description: Allows players to reload config
    default: op

  blocklobber.admin:
    description: Grants all admin permissions
    children: 
      blocklobber.reload: true
  
  blocklobber.block:
    description: Grants all block lobbing permissions
    children:
      blocklobber.lob: true
      blocklobber.preset: true
      
  blocklobber.projectile:
    description: Grants all projectile lobbing permissions
    children:
      blocklobber.projectile.lob: true
      blocklobber.projectile.preset: true
    
  blocklobber.*:
    description: Grants all permissions
    children:
      blocklobber.lob: true
      blocklobber.preset: true
      blocklobber.reload: true
      blocklobber.projectile.lob: true
      blocklobber.projectile.preset: true
